In [1]:
import numpy as np
import pandas as pd

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/ML projects/Datasets/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/drive/MyDrive/ML projects/Datasets/tmdb_5000_credits.csv')

In [ ]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
credits.head(3)['cast'].values[2]

'[{"cast_id": 1, "character": "James Bond", "credit_id": "52fe4d22c3a368484e1d8d6b", "gender": 2, "id": 8784, "name": "Daniel Craig", "order": 0}, {"cast_id": 14, "character": "Blofeld", "credit_id": "54805866c3a36829ab002592", "gender": 2, "id": 27319, "name": "Christoph Waltz", "order": 1}, {"cast_id": 13, "character": "Madeleine", "credit_id": "546f934fc3a3682f9a002ca5", "gender": 1, "id": 121529, "name": "L\\u00e9a Seydoux", "order": 2}, {"cast_id": 10, "character": "M", "credit_id": "53e86503c3a368399c0031f0", "gender": 2, "id": 5469, "name": "Ralph Fiennes", "order": 3}, {"cast_id": 17, "character": "Lucia", "credit_id": "54805920c3a36829ae0022c5", "gender": 1, "id": 28782, "name": "Monica Bellucci", "order": 4}, {"cast_id": 8, "character": "Q", "credit_id": "52fe4d22c3a368484e1d8d87", "gender": 2, "id": 17064, "name": "Ben Whishaw", "order": 5}, {"cast_id": 11, "character": "Moneypenny", "credit_id": "53e8650cc3a368399c0031f4", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 6}, {"cast_id": 16, "character": "Hinx", "credit_id": "5480590f9251416e7b0022f4", "gender": 2, "id": 543530, "name": "Dave Bautista", "order": 7}, {"cast_id": 15, "character": "C", "credit_id": "548058ffc3a36829a7002511", "gender": 2, "id": 125660, "name": "Andrew Scott", "order": 8}, {"cast_id": 19, "character": "Tanner", "credit_id": "5480593cc3a36829ae0022ca", "gender": 2, "id": 139549, "name": "Rory Kinnear", "order": 9}, {"cast_id": 23, "character": "Mr. White", "credit_id": "5517b3849251416f0d0032c8", "gender": 2, "id": 2244, "name": "Jesper Christensen", "order": 10}, {"cast_id": 24, "character": "Marco Sciarra", "credit_id": "5517b398c3a36862fc002df6", "gender": 0, "id": 1381616, "name": "Alessandro Cremona", "order": 11}, {"cast_id": 25, "character": "Estrella", "credit_id": "5517b3c49251412c1e00180b", "gender": 1, "id": 929937, "name": "Stephanie Sigman", "order": 12}, {"cast_id": 49, "character": "Mexican Man in Lift", "credit_id": "5664561cc3a3682bd0007fc8", "gender": 0, "id": 87265, "name": "Tenoch Huerta", "order": 13}, {"cast_id": 50, "character": "Mexican Woman in Lift", "credit_id": "5664561dc3a3682be9008dc6", "gender": 1, "id": 983710, "name": "Adriana Paz", "order": 14}, {"cast_id": 180, "character": "Gallo", "credit_id": "56fddbacc3a36821b6000aca", "gender": 2, "id": 1385592, "name": "Domenico Fortunato", "order": 15}, {"cast_id": 51, "character": "Gallo\'s Accomplice", "credit_id": "5664561dc3a3682bd8008fbe", "gender": 0, "id": 1545546, "name": "Marco Zingaro", "order": 16}, {"cast_id": 52, "character": "Gallo\'s Accomplice", "credit_id": "5664561d9251412ad300870b", "gender": 2, "id": 1545547, "name": "Stefano Elfi DiClaudia", "order": 17}, {"cast_id": 181, "character": "Q\'s Assistant", "credit_id": "56fddc319251412a4d0009f9", "gender": 0, "id": 122556, "name": "Ian Bonar", "order": 18}, {"cast_id": 182, "character": "Moneypenny\'s Boyfriend", "credit_id": "56fddc66c3a36821b6000b04", "gender": 2, "id": 1599239, "name": "Tam Williams", "order": 19}, {"cast_id": 183, "character": "Blofeld\'s London Helicopter Pilot", "credit_id": "56fddc989251412a56000a85", "gender": 2, "id": 1599241, "name": "Richard Banham", "order": 20}, {"cast_id": 184, "character": "SC019 Police Commander", "credit_id": "56fddccf9251412a4b000b5d", "gender": 2, "id": 230681, "name": "Pip Carter", "order": 21}, {"cast_id": 185, "character": "SC019 Police Officer", "credit_id": "56fddce6c3a36821ae000b45", "gender": 2, "id": 30446, "name": "Simon Lenagan", "order": 22}, {"cast_id": 27, "character": "Priest", "credit_id": "5517b4f69251416efe003370", "gender": 2, "id": 48377, "name": "Alessandro Bressanello", "order": 23}, {"cast_id": 38, "character": "Moreau", "credit_id": "56486811c3a3682605006adc", "gender": 0, "id": 578512, "name": "Marc Zinga", "order": 24}, {"cast_id": 39, "character": "Vogel", "credit_id": "56486820c3a368261a006de7", "gender": 0, "id": 1093974, "name": "Brigitte Millar", "order": 25}, {"cast_id": 41, "character": "Abrika", "credit_id": "564868a09251413ad7006da5", "gender": 2, "id": 89624, "name": "Adel Bencherif", "order": 26}, {"cast_id": 186, "character": "Blofeld\'s Right Hand Man", "credit_id": "56fddd5a9251412a42000b52", "gender": 2, "id": 1129783, "name": "Gediminas Adomaitis", "order": 27}, {"cast_id": 42, "character": "Lorenzo", "credit_id": "564868c5c3a368260c006ee4", "gender": 0, "id": 226388, "name": "Peppe Lanzetta", "order": 28}, {"cast_id": 187, "character": "Francesco", "credit_id": "56fddd9cc3a36821a4000b5b", "gender": 2, "id": 1299312, "name": "Francesco Arca", "order": 29}, {"cast_id": 188, "character": "Marco", "credit_id": "56fdddb79251412a50000aad", "gender": 2, "id": 124628, "name": "Matteo Taranto", "order": 30}, {"cast_id": 189, "character": "Palazzo Security", "credit_id": "56fdddd69251412a56000ac6", "gender": 2, "id": 1562103, "name": "Emilio Aniba", "order": 31}, {"cast_id": 190, "character": "Guerra", "credit_id": "56fdddf19251412a50000ac1", "gender": 2, "id": 1474616, "name": "Benito Sagredo", "order": 32}, {"cast_id": 191, "character": "Businessman", "credit_id": "56fdde0d9251416cc200004c", "gender": 2, "id": 1247684, "name": "Dai Tabuchi", "order": 33}, {"cast_id": 192, "character": "Businessman", "credit_id": "56fdde1bc3a36821b1000ba8", "gender": 2, "id": 1599245, "name": "George Lasha", "order": 34}, {"cast_id": 193, "character": "Businessman", "credit_id": "56fdde259251412a42000b93", "gender": 0, "id": 1599247, "name": "Sargon Yelda", "order": 35}, {"cast_id": 194, "character": "Businessman", "credit_id": "56fdde9fc3a36821b6000ba0", "gender": 2, "id": 1599251, "name": "Andy Cheung", "order": 36}, {"cast_id": 195, "character": "Marshall", "credit_id": "56fddeb29251412a50000af4", "gender": 2, "id": 1599252, "name": "Erick Hayden", "order": 37}, {"cast_id": 196, "character": "Valerian", "credit_id": "56fddec8c3a36821ab000c19", "gender": 2, "id": 1599253, "name": "Oleg Mirochnikov", "order": 38}, {"cast_id": 197, "character": "Fiat Driver", "credit_id": "56fddef89251412a47000a79", "gender": 2, "id": 123548, "name": "Antonio Salines", "order": 39}, {"cast_id": 198, "character": "Street Sweeper", "credit_id": "56fddf109251416cc2000086", "gender": 2, "id": 1599254, "name": "Miloud Mourad Benamara", "order": 40}, {"cast_id": 199, "character": "Chairman", "credit_id": "56fddf4a9251412a42000bcf", "gender": 2, "id": 1599255, "name": "Gido Schimanski", "order": 41}, {"cast_id": 200, "character": "Head of Nation", "credit_id": "56fddf69c3a36821a7000b12", "gender": 0, "id": 1404403, "name": "Nigel Barber", "order": 42}, {"cast_id": 201, "character": "Head of Nation", "credit_id": "56fddf7fc3a36821b1000c0d", "gender": 2, "id": 74415, "name": "Patrice Naiambana", "order": 43}, {"cast_id": 202, "character": "Head of Nation", "credit_id": "56fddf89c3a368219d000adb", "gender": 2, "id": 1599256, "name": "Stephane Cornicard", "order": 44}, {"cast_id": 203, "character": "Head of Nation", "credit_id": "56fddf929251412a56000b29", "gender": 2, "id": 1599257, "name": "Gary Fannin", "order": 45}, {"cast_id": 204, "character": "Head of Nation", "credit_id": "56fddf9cc3a36821ae000be1", "gender": 2, "id": 1599258, "name": "Sadao Ueda", "order": 46}, {"cast_id": 205, "character": "Head of Nation", "credit_id": "56fddfb99251412a50000b30", "gender": 0, "id": 1599259, "name": "Phillip Law", "order": 47}, {"cast_id": 206, "character": "Head of Nation", "credit_id": "56fddfef9251412a54000ba8", "gender": 2, "id": 1599260, "name": "Wai Wong", "order": 48}, {"cast_id": 207, "character": "Head of Nation", "credit_id": "56fde0179251412a47000ac2", "gender": 2, "id": 1477143, "name": "Joseph Balderrama", "order": 49}, {"cast_id": 208, "character": "Aide", "credit_id": "56fde0809251416cc20000cb", "gender": 2, "id": 1599261, "name": "Eiji Mihara", "order": 50}, {"cast_id": 209, "character": "Aide", "credit_id": "56fde0a49251412a47000ae0", "gender": 2, "id": 1168129, "name": "Junichi Kajioka", "order": 51}, {"cast_id": 40, "character": "Clinic Barman", "credit_id": "56486850c3a368260c006ecf", "gender": 0, "id": 48393, "name": "Victor Schef\\u00e9", "order": 52}, {"cast_id": 210, "character": "Clinic Security Guard", "credit_id": "56fde0f19251412a42000c28", "gender": 2, "id": 1437333, "name": "Harald Windisch", "order": 53}, {"cast_id": 211, "character": "Clinic Security Guard", "credit_id": "56fde118c3a36821a4000c3c", "gender": 2, "id": 1599262, "name": "Tristan Matthiae", "order": 54}, {"cast_id": 177, "character": "Cable Car Heavy", "credit_id": "5696db21c3a3683af90002d6", "gender": 2, "id": 14637, "name": "Detlef Bothe", "order": 55}, {"cast_id": 212, "character": "Cable Car Heavy", "credit_id": "56fde128c3a368219d000b4f", "gender": 2, "id": 1599263, "name": "Bodo Friesecke", "order": 56}, {"cast_id": 213, "character": "Syringe Heavy", "credit_id": "56fde1769251412a54000c0b", "gender": 2, "id": 1599264, "name": "Wilhem Iben", "order": 57}, {"cast_id": 214, "character": "Snowboarder", "credit_id": "56fde1849251412a42000c4d", "gender": 1, "id": 1599265, "name": "Noemi Krausz", "order": 58}, {"cast_id": 215, "character": "Snowboarder", "credit_id": "56fde18dc3a36821b6000c4f", "gender": 2, "id": 1599266, "name": "Noah Saavedra", "order": 59}, {"cast_id": 216, "character": "Snowboarder", "credit_id": "56fde1989251412a54000c16", "gender": 0, "id": 1599267, "name": "Francis Attakpah", "order": 60}, {"cast_id": 217, "character": "Snowboarder", "credit_id": "56fde1a39251412a42000c58", "gender": 2, "id": 1599268, "name": "Michael Glantschnig", "order": 61}, {"cast_id": 218, "character": "Snowboarder", "credit_id": "56fde1aec3a36821ab000cbf", "gender": 2, "id": 1599269, "name": "Marlon Boess", "order": 62}, {"cast_id": 219, "character": "Snowboarder", "credit_id": "56fde1b8c3a36821ae000c62", "gender": 1, "id": 1599270, "name": "Marie Wohlmuth", "order": 63}, {"cast_id": 220, "character": "Snowboarder", "credit_id": "56fde1c1c3a36821b1000c9c", "gender": 1, "id": 1599271, "name": "Lili Epply", "order": 64}, {"cast_id": 221, "character": "Snowboarder", "credit_id": "56fde1cbc3a36821a7000baf", "gender": 2, "id": 1599272, "name": "Konstantin Gerlach", "order": 65}, {"cast_id": 222, "character": "L\'Americain Manater", "credit_id": "56fde24c9251412a45000bfb", "gender": 1, "id": 1102369, "name": "Lara Parmiani", "order": 66}, {"cast_id": 223, "character": "Train Guard", "credit_id": "56fde2679251412a54000c42", "gender": 2, "id": 1372694, "name": "Umit Ulgen", "order": 67}, {"cast_id": 224, "character": "Train Waiter", "credit_id": "56fde2869251412a50000bf1", "gender": 2, "id": 1363060, "name": "Amra Mallassi", "order": 68}, {"cast_id": 225, "character": "Train Barman", "credit_id": "56fde2969251412a45000c15", "gender": 2, "id": 1599275, "name": "Ziad Abaza", "order": 69}, {"cast_id": 226, "character": "Blofeld\'s Chauffeur", "credit_id": "56fde2a79251412a54000c55", "gender": 2, "id": 1599276, "name": "Walid Mumuni", "order": 70}, {"cast_id": 227, "character": "Blofeld\'s Guard", "credit_id": "56fde2eb9251416cc200015b", "gender": 0, "id": 1599277, "name": "Derek Horsham", "order": 71}, {"cast_id": 228, "character": "Blofeld\'s Guard", "credit_id": "56fde3059251412a47000b6a", "gender": 2, "id": 229320, "name": "Nari Blair-Mangat", "order": 72}, {"cast_id": 229, "character": "Blofeld\'s Butler", "credit_id": "56fde321c3a36821ab000d32", "gender": 0, "id": 1599278, "name": "Michael White", "order": 73}, {"cast_id": 230, "character": "Blofeld\'s Waiter", "credit_id": "56fde34c9251412a56000c21", "gender": 0, "id": 1599279, "name": "Adam McGrady", "order": 74}, {"cast_id": 231, "character": "Blofeld\'s Analyst", "credit_id": "56fde36d9251412a50000c2b", "gender": 2, "id": 1436816, "name": "Nader Dernaika", "order": 75}, {"cast_id": 232, "character": "Blofeld\'s Chief Analyst", "credit_id": "56fde37f9251412a4b000cf7", "gender": 2, "id": 1599280, "name": "Pezhmaan Alinia", "order": 76}, {"cast_id": 31, "character": "M (uncredited)", "credit_id": "562f218fc3a3681b5200c9e5", "gender": 1, "id": 5309, "name": "Judi Dench", "order": 77}, {"cast_id": 26, "character": "Clinic Patron (uncredited)", "credit_id": "5517b4bbc3a3686302002f36", "gender": 1, "id": 1186597, "name": "Neve Gachev", "order": 78}, {"cast_id": 245, "character": "Businessman (uncredited)", "credit_id": "57e11a3e92514104570052ba", "gender": 2, "id": 1654739, "name": "Karl Farrer", "order": 79}, {"cast_id": 246, "character": "Lair Staff (uncredited)", "credit_id": "57e124d992514104530055ec", "gender": 1, "id": 1682535, "name": "Kim Adis", "order": 80}, {"cast_id": 247, "character": "Mexican Sprite (uncredited)", "credit_id": "57e125ccc3a36853f2005365", "gender": 1, "id": 1682536, "name": "Maurisa Selene Coleman", "order": 81}, {"cast_id": 249, "character": "Pilot David", "credit_id": "585ab69fc3a3682fb8091219", "gender": 2, "id": 1725801, "name": "Matija Mondi Matovi\\u0107", "order": 82}]'

In [ ]:
movies_new = movies.merge(credits, on='title')

In [ ]:
movies_new.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
# important colums for working:
# genres, movie_id, keywords, title, overview, cast, crew

In [ ]:
# Now we are creating a new DataFrame now we focus on these specific colums
movies_new = movies_new[['movie_id','title', 'overview', 'genres', 'keywords', 'cast','crew']]

In [ ]:
# This will show you all languages of dataset movies
# movies_new['original_language'].value_counts()

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
# This code will check how much null values are present in dataset
movies_new.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
# This code will remove all those rows which contain null data
movies_new.dropna(inplace=True)

In [ ]:
# this code show you duplicated data of DataFrame
movies.duplicated().sum()

0

In [ ]:
# This code ( iloc ) selects the index row (index 0) of the DataFrame
movies_new.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
# [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# now we convert it into preprocessing format like
# ['Action', 'Adventure', 'Fantasy', 'Science Fiction']
# ast.literal_eval -> It's designed to handle simple Python data structures like lists, dictionaries, and basic types.

In [ ]:
import ast
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [ ]:
# Now genres colum store specific values
movies_new['genres'] = movies_new['genres'].apply(convert)

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
# Now keywords colum store specific values
movies_new['keywords'] = movies_new['keywords'].apply(convert)

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
# Now we fetch (Main/First) three movie hero names
def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter +=1
    else:
      break
  return L

In [ ]:
movies_new['cast'] = movies_new['cast'].apply(convert3)

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
# Now we find director name from crew table
def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

In [ ]:
movies_new['crew'] = movies_new['crew'].apply(fetch_director) # Pass the function object, not a string

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:
# Now we convert string of overview column into list
movies_new['overview'] = movies_new['overview'].apply(lambda x:x.split())

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:
# This code remove all blank spaces from these colums
movies_new['genres'] = movies_new['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies_new['keywords'] = movies_new['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies_new['cast'] = movies_new['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies_new['crew'] = movies_new['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [ ]:
# Now we concatenate or merge last 4 columns into a new column tag
movies_new['tag'] = movies_new['overview'] + movies_new['genres'] +movies_new['cast'] +movies_new['crew']

In [ ]:
movies_new.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [ ]:
# Now we make new data frame by using preprocessing
new_df = movies_new[['movie_id', 'title', 'tag']]

In [ ]:
new_df.head(2)

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."

In [ ]:
# Now we convert list into string
new_df['tag'] = new_df['tag'].apply(lambda x:" ".join(x))

<ipython-input-36-8fc7fd1b9453>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(lambda x:" ".join(x))

In [ ]:
new_df.head(2)

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."

In [ ]:
# this code convert similer words into one word like( love, loving, loved =love)
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
# Now we write a streaming function to stem the words mean it convert (loved, loving into love ,,etc,,)
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))  # Append stemmed word to the list
  return " ".join(y)  # Return the joined stemmed string after processing all words

In [ ]:
new_df['tag'] =new_df['tag'].apply(stem)

<ipython-input-40-bdb23bc33a7a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] =new_df['tag'].apply(stem)

In [ ]:
new_df['tag'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [ ]:
new_df['tag'] = new_df['tag'].apply(lambda x:x.lower())

<ipython-input-42-f9c79f0acdd8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(lambda x:x.lower())

In [ ]:
new_df.head(2)

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."

In [ ]:
# This code is used for extract (5000) words and remove all stop words of english(is, it, the, to, etc)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
# Now we apply upper code on our new_df datasets tag column
cv.fit_transform(new_df['tag']).toarray().shape

(4806, 5000)

In [ ]:
# this code convert all string data of tag into array vectors
vectors = cv.fit_transform(new_df['tag']).toarray()

In [ ]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# This code will give us the most popular 5000 words which we need
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [ ]:
len(cv.get_feature_names_out())

5000

In [ ]:
ps.stem('danced')

'danc'

In [ ]:
# Now streaming function is applied on it
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction Sam Worthington Zoe Saldana Sigourney Weaver James Cameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction sam worthington zoe saldana sigourney weaver jame cameron'

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(vectors)

array([[1.        , 0.13957263, 0.08206099, ..., 0.        , 0.        ,
        0.        ],
       [0.13957263, 1.        , 0.08399211, ..., 0.03253   , 0.        ,
        0.03539962],
       [0.08206099, 0.08399211, 1.        , ..., 0.02868877, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03253   , 0.02868877, ..., 1.        , 0.04444444,
        0.02418254],
       [0.        , 0.        , 0.        , ..., 0.04444444, 1.        ,
        0.09673017],
       [0.        , 0.03539962, 0.        , ..., 0.02418254, 0.09673017,
        1.        ]])

In [ ]:
similarity = cosine_similarity(vectors)

In [ ]:
similarity

array([[1.        , 0.13957263, 0.08206099, ..., 0.        , 0.        ,
        0.        ],
       [0.13957263, 1.        , 0.08399211, ..., 0.03253   , 0.        ,
        0.03539962],
       [0.08206099, 0.08399211, 1.        , ..., 0.02868877, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03253   , 0.02868877, ..., 1.        , 0.04444444,
        0.02418254],
       [0.        , 0.        , 0.        , ..., 0.04444444, 1.        ,
        0.09673017],
       [0.        , 0.03539962, 0.        , ..., 0.02418254, 0.09673017,
        1.        ]])

In [ ]:
# If we enter 0 in Square brackets then it will give array of first movie and if we write 1 then it will give me array of second movie and up to so on...
similarity[0]

array([1.        , 0.13957263, 0.08206099, ..., 0.        , 0.        ,
       0.        ])

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x:x[1])[1:6]

[(2999, 0.25854384499750954),
 (4405, 0.24618298195866548),
 (61, 0.23262105259961768),
 (1444, 0.2279211529192759),
 (942, 0.22498852128662875)]

In [ ]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:6]
  for i in movies_list:
    print(new_df.iloc[i[0]]. title)
  return

In [ ]:
recommend('Batman Begins')

Synecdoche, New York
10th & Wolf
American Psycho
Sexy Beast
Copying Beethoven

In [ ]:
new_df.iloc[2999]. title

'Mad Max Beyond Thunderdome'

In [ ]:
import pickle

# Convert the DataFrame to a dictionary
movie_dict = new_df.to_dict(orient='list')

# Save the dictionary to a pickle file
pickle.dump(movie_dict, open('movie_dict.pkl', 'wb'))

In [ ]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))